name: publish
on:
  push:
    branches: [master]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: yarn
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - name: Git configuration.
        run: |
          git config --global user.email bot@example
          git config --global user.name bot
      - name: Publish.
        run: |
          npm version patch
          git push --atomic --tags origin HEAD
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
